# ==========================
# Configurazione generale
# ==========================
compose_file: "../env/docker-compose.yml"    # Percorso del file docker-compose
results_dir: "../results"                 

# ==========================
# Container e connessioni
# ==========================
container_initiator: "initiator_classic"    # initiator_minimal | initiator_classic
container_responder: "responder"          # Nome del container responder
connection_name: "minimal"                 # rinominare in classical e post-quantum

# ==========================
# Simulazione e iterazioni
# ==========================
iterations: 5           # Numero di iterazioni della negoziazione IKE
