services:
  vpn-server:
    build: .
    container_name: strongswan
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_MODULE
    stdin_open: true
    tty: true
    volumes:
      - "./log:/var/log"
      - "./swanctl:/etc/swanctl"
      - "./strongswan.conf:/etc/strongswan.conf"
    command: ["sh", "-c", "/usr/libexec/ipsec/charon"]
