services:
  moon:
    image: strongx509/strongswan:latest
    container_name: moon
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_MODULE
    stdin_open: true
    tty: true
    volumes:
      - ./server/swanctl:/etc/swanctl
      - ./server/strongswan.conf:/etc/strongswan.conf
    command: ["sh", "-c", "/usr/libexec/ipsec/charon"]
    networks:
      pmtud-net:
        ipv4_address: 192.168.100.2
  vpn-client:
    image: strongx509/strongswan:latest
    container_name: client
    depends_on:
      - moon
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_MODULE
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '1.0'   # Limita a 1 CPU in generale
    cpuset: "0"  

    command: ["sh", "-c", "/usr/libexec/ipsec/charon"]
    volumes:
      - ./client/swanctl:/etc/swanctl
      - ./client/strongswan.conf:/etc/strongswan.conf
      - ./keys:/var/log
    networks:
      pmtud-net:
         ipv4_address: 192.168.100.3

  minimal:
    build: minimal_ike
    container_name: ike
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_MODULE
    networks:
      pmtud-net:
         ipv4_address: 192.168.100.5

networks:
  pmtud-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
    driver_opts:
      com.docker.network.driver.mtu: 1500

